import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';

export default defineConfig({
  site: 'https://www.atriumlivings.com',
  redirects: {
    "/ultimate-stamped-concrete-patio-guide": "/",
    "/how-to-remove-sink-stopper-modern-luxury-living-rooms": "/",
    "/custom-raised-vegetable-garden-beds-wood-design-concepts": "/",
    "/choosing-best-color-for-bathroom-spaces": "/",
    "/mastering-design-with-cheap-paving-slabs-and-stone": "/",
    "/how-to-specify-your-luxury-nightstand-and-dresser-layouts": "/",
    "/ashley-furniture-maribel-panel-bed-architectural-blueprint": "/",
    "/mastering-mid-century-modern-art-in-luxury-homes": "/",
    "/outdoor-dining-near-me-architectural-guide": "/",
    "/purple-mattress-review-and-sleep-architecture": "/",
    "/designing-luxury-spaces-with-exquisite-doll-house-furniture": "/",
    "/architectural-guide-specifying-exterior-wall-tiles": "/",
    "/modern-slabs-for-garden-spaces": "/",
    "/where-to-buy-mattress-architectural-guide": "/",
    "/curated-courtyard-garden-landscape-design-guide": "/",
    "/designing-with-lamp-shades-and-architectural-lighting": "/",
    "/finding-exceptional-furniture-shops-close-to-me": "/",
    "/art-and-craft-for-students-studio-design": "/",
    "/elevated-raised-garden-bed-ideas-for-luxury-bedroom-spaces": "/",
    "/house-to-draw-a-house-architectural-mastery": "/",
    "/premier-bathroom-accessories-for-small-bathroom-layouts": "/",
    "/kitchen-ideas-architectural-guide": "/",
    "/current-trends-modern-luxury-architecture": "/",
    "/innovative-small-apartment-ideas-luxury-micro-living": "/",
    "/designing-elegant-spaces-for-garden-implements-and-tools": "/",
    "/mastering-elegance-creative-diy-home-decor-ideas": "/",
    "/mastering-diy-home-renovation-spaces-and-structural-design": "/",
    "/lights-on-a-ceiling-modern-homes": "/",
    "/mastering-advanced-decoration-room-decoration-techniques": "/",
    "/the-complete-architectural-manual-to-size-bedrooms-today": "/",
    "/why-house-drawing-rules-modern-luxury-living-room-design": "/",
    "/mastering-advanced-luxury-kitchen-design-ideas-today": "/",
    "/mastering-modern-interior-design-trends-for-luxury-spaces": "/",
    "/designing-modern-small-apartment-luxury-living-space": "/",
    "/selecting-premium-gardening-tools-luxury-estates": "/",
    "/compact-dining-table-layout-ideas-for-small-spaces": "/",
    "/professional-architectural-design-guide-for-diy-projects": "/",
    "/how-home-renovation-shows-influence-real-luxury-projects": "/",
    "/designing-luxury-low-voltage-landscape-lighting": "/",
    "/architectural-dining-room-table-dining-room-guide": "/",
    "/smart-home-automation-engineering-modern-luxury-residences": "/",
    "/bedroom-ideas-architectural-guide": "/",
    "/architectural-home-office-ideas-for-modern-living-spaces": "/",
    "/mastering-disenos-de-banos-for-modern-luxury-living": "/",
    "/mastering-ultimate-luxury-accessory-set-bathroom-design": "/",
    "/crafting-the-ultimate-modern-kitchen-design-blueprint": "/",
    "/architectural-master-planning-king-bed-set": "/",
    "/how-to-style-a-luxury-king-bed-set": "/",
    "/how-to-style-a-luxury-king-bed-set-master-bedroom-guide": "/",
    "/luxury-king-bed-set-guide": "/"
},
  integrations: [],
  server: {
    port: 3000,
    host: true
  }
});
